version: '3.9'

services:
  post-and-comments:
    build: ./
    command: ./post-and-comments
    ports:
      - 8000:8000
    depends_on:
      - db
    environment:
      - DB_PASSWORD=password

  db:
    restart: always
    image: postgres:latest
    volumes:
      - ./db/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: postsandcomments
      DATABASE_URL: "postgres://user:password@db:5432/postsandcomments?sslmode=disable"
    ports:
      - "5432:5432"
