// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Comment struct {
	ID              string     `json:"id"`
	PostID          string     `json:"postID"`
	ParentCommentID *string    `json:"parentCommentID,omitempty"`
	AuthorID        string     `json:"authorID"`
	Text            string     `json:"text"`
	Children        []*Comment `json:"children,omitempty"`
}

type CommentInput struct {
	PostID          string  `json:"postID"`
	ParentCommentID *string `json:"parentCommentID,omitempty"`
	AuthorID        string  `json:"authorID"`
	Text            string  `json:"text"`
}

type Mutation struct {
}

type Post struct {
	ID            string     `json:"id"`
	Title         string     `json:"title"`
	Content       string     `json:"content"`
	AuthorID      string     `json:"authorID"`
	AllowComments bool       `json:"allowComments"`
	Comments      []*Comment `json:"comments,omitempty"`
}

type PostInput struct {
	Title         string `json:"title"`
	Content       string `json:"content"`
	AuthorID      string `json:"authorID"`
	AllowComments bool   `json:"allowComments"`
}

type Query struct {
}

type Subscription struct {
}
